use "match case" instead of "if else"
Datapack-Hub/bot pull request #3
Opened 2023-09-29 09:42 UTC by Rignchen

while looking in the code I realise there was a lot of
```py
if variable == "value 1":
    ...
elif variable == "value 2":
    ...
elif variable == "value 3":
    ...
elif ...
```
wich can easily be change to a switch case:
```py
match variable:
    case "value 1":
        ...
    case "value 2":
        ...
    case "value 3":
        ...
    case ...
```
wich is both a cleaner and more optimized way to do the same thing

2023-09-29 10:53 UTC, HoodieRocks commented
Match case was only recently added in 3.10, I don't know what version our host is using though.

2023-09-30 11:00 UTC, FIyrr reviewed
what exactly does this do? :P (reffering to the convention.debug thingy)

2023-09-30 11:01 UTC, FIyrr commented on cogs/commands/invite.py
> +                    description="Rejoins Data World pour obtenir de l'aide sur les datapacks avec le lien: https://discord.gg/5y5FBz5",
Since the bot is english, could you maybe translate this to english too?

2023-09-30 11:02 UTC, FIyrr requested changes
Since the bot is english, i think it would be more fitting to have the description in english here too :P

2023-09-30 20:47 UTC, Rignchen commented
> what exactly does this do? :P (reffering to the convention.debug thingy)

the convention.debug is a tag you manualy give yourself when you dev cause you don't want people who download your datapack to see debug messages (an exemple of message we don't want them to see is the tellraw in the load.mcfunction cause if every datapack send one then the chat just gets spam)

2023-09-30 20:47 UTC, Rignchen commented
> Since the bot is english, i think it would be more fitting to have the description in english here too :P

I chosed to translate the description of the server in french as the server is in french (that's why there's a "(fr)" in the name) so I thaught that people who would request this link would prefer a french description

2023-09-30 20:50 UTC, Rignchen commented
> Match case was only recently added in 3.10, I don't know what version our host is using though.

python 3.10 was released on Oct. 4, 2021, if your host is still on an older version you should maybe consider looking for a new one

2023-09-30 21:37 UTC, HoodieRocks commented
Valid, LGTM, but flyne gets the last decision obv

2023-10-01 09:37 UTC, FIyrr commented
> > Since the bot is english, i think it would be more fitting to have the description in english here too :P
> 
> I chosed to translate the description of the server in french as the server is in french (that's why there's a "(fr)" in the name) so I thaught that people who would request this link would prefer a french description

i know that the server is in french and understand your argument, but at the same time someone else might just be browsing through servers included in the command and be confused by a french description

2023-10-01 09:39 UTC, FIyrr commented
> > what exactly does this do? :P (reffering to the convention.debug thingy)
> 
> the convention.debug is a tag you manualy give yourself when you dev cause you don't want people who download your datapack to see debug messages (an exemple of message we don't want them to see is the tellraw in the load.mcfunction cause if every datapack send one then the chat just gets spam)

the tellraw in the load function is there to let people know that the pack sucessfully loaded?
this is not just for the devs convenience but especially for everyone using the pack as that message might also contain information about sources and contributors to the pack
we better don't start randomly including convention related stuff in the bot since this is meant to be a completely "vanilla" datapack template and we don't want to force people to use conventions

2023-10-01 09:40 UTC, FIyrr commented
> > Match case was only recently added in 3.10, I don't know what version our host is using though.
> 
> python 3.10 was released on Oct. 4, 2021, if your host is still on an older version you should maybe consider looking for a new one

yea the vps is running python 3.10.4 so that won't be a problem

2023-10-03 08:44 UTC, merged